version: '3.9'

services:
  asterisk:
    container_name: asterisk
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "8080:8080/udp"
      - "8080:8080/tcp"
    network_mode: host

networks:
  asterisk_net:
    driver: host